plugins {
    id 'fml-loom' version '0.1'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = "Spongepowered"
        url = "https://repo.spongepowered.org/repository/maven-public/"
    }
    maven {
        name = "ModdedMITE"
        url = "https://maven.limingzxc.top/repository/maven-public/"
    }
}

configurations {
    fml
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    fml "com.github.MinecraftIsTooEasy:FishModLoader:${project.fml_version}"
    implementation "com.github.MinecraftIsTooEasy:FishModLoader:${project.fml_version}"
}

def fmlResolvedFile = configurations.fml.files.iterator().next()

loom {
    accessWidenerPath = file("src/main/resources/ingameime.accesswidener")
    mergedMinecraftJar()
    setFML(fmlResolvedFile)
    dependencies.add("mappings", fmlMCPMappings())
    mods {
        "ingameime" {
            sourceSet sourceSets.main
        }
    }
    runs {
        client {
            String name = project.username
            String width = project.screen_width
            String height = project.screen_height
            programArgs "--userProperties", "{}", "--username", name, "--session", "a.a.a.a", "--width", width, "--height", height
        }
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fml.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
    it.options.encoding = 'UTF-8'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from("LICENSE")
}
